import Link from 'next/link';
import { JsonLd } from '@/components/json-ld';
import { createMetadata } from '@/lib/seo';
import { absoluteUrl, site } from '@/lib/site';

export const metadata = createMetadata({ title: 'About Viththiyakaran Nadarajah', description: 'Meet Viththiyakaran Nadarajah, a software developer and IT professional in Newtown, Powys, with engineering, support and operational experience.', path: '/about' });

export default function AboutPage() {
  return <><JsonLd data={{ '@context': 'https://schema.org', '@type': 'ProfilePage', url: absoluteUrl('/about'), name: `About ${site.name}`, mainEntity: { '@type': 'Person', '@id': `${site.url}/#person`, name: site.name, jobTitle: ['Software Developer', 'IT Support Professional'], homeLocation: { '@type': 'Place', name: site.location }, alumniOf: [{ '@type': 'EducationalOrganization', name: 'UWE Bristol' }] } }} />
    <header className="page-head"><div className="shell intro-grid"><div><p className="eyebrow">Viththiyakaran Nadarajah</p><h1>Software Developer and IT Professional</h1><p className="lede">I combine previous software engineering and technical support experience with current UK operational responsibility, giving me a practical view of both systems and the people who depend on them.</p></div><aside className="profile-summary"><strong>Professional summary</strong><ul><li>Based in Newtown, Powys</li><li>UK right to work without sponsorship</li><li>Available for Wales-based, hybrid and UK remote roles</li><li>Interested in development, support, systems and junior cloud work</li></ul></aside></div></header>
    <section className="section"><div className="shell about-layout"><article className="prose"><h2>Technical background</h2><p>My background includes a B.Tech in Software Technology and MSc IT studies at UWE Bristol. I have previous software engineering experience, previous technical support experience and working knowledge of C#, .NET, React, TypeScript and SQL. I am also developing my AWS cloud knowledge.</p><p>I approach software as an operational tool rather than an isolated technical exercise. Requirements, accessibility, security, diagnostics and recovery all influence whether an application is genuinely useful.</p><h2>Operational experience that strengthens my IT work</h2><p>My current UK operational and supervisory experience builds leadership, responsibility, compliance awareness, customer service, problem solving, team coordination and business-process understanding. These strengths are valuable in application support and software delivery, where clear communication and calm ownership matter alongside technical ability.</p><p>This current role is part of my professional story, but it does not replace my software direction. I am actively positioning for software development, application support, IT support, systems and junior cloud opportunities.</p><h2>How I work</h2><p>I prefer honest scope, maintainable solutions and visible trade-offs. Portfolio concepts are labelled as concepts or architecture studies, and proposed technologies are separated from implemented ones.</p><p>Continue to the <Link href="/experience">editable experience timeline</Link>, inspect my <Link href="/projects">software project case studies</Link>, or <Link href="/contact">discuss a suitable opportunity</Link>.</p></article><aside className="side-card"><strong>Core technologies</strong><ul><li>C# and .NET</li><li>React and TypeScript</li><li>SQL and relational data</li><li>Application and technical support</li><li>AWS cloud foundations</li></ul><a className="button" href="/viththiyakaran-nadarajah-cv.pdf" download>Download my CV</a></aside></div></section>
  </>;
}
