import Link from 'next/link';
import { JsonLd } from '@/components/json-ld';
import { createMetadata } from '@/lib/seo';
import { absoluteUrl, site } from '@/lib/site';

export const metadata = createMetadata({ title: 'About Viththiyakaran Nadarajah', description: 'Meet Viththiyakaran Nadarajah, a software developer and IT professional in Newtown, Powys, with engineering, support and operational experience.', path: '/about' });

export default function AboutPage() {
  return <><JsonLd data={{ '@context': 'https://schema.org', '@type': 'ProfilePage', url: absoluteUrl('/about'), name: `About ${site.name}`, mainEntity: { '@type': 'Person', '@id': `${site.url}/#person`, name: site.name, jobTitle: ['Software Developer', 'IT Support Professional'], homeLocation: { '@type': 'Place', name: site.location }, alumniOf: [{ '@type': 'EducationalOrganization', name: 'UWE Bristol' }] } }} />
    <header className="page-head about-head"><div className="shell about-intro"><div className="identity-graphic" aria-label="VN identity graphic"><span>VN</span><small>Newtown · Wales</small></div><div><p className="eyebrow">About</p><h1>Viththiyakaran Nadarajah</h1><p className="role-title">Software Developer and IT Professional</p><p className="lede">I combine previous software engineering and technical support experience with current UK operational responsibility, giving me a practical view of both systems and the people who depend on them.</p><ul className="tags key-areas" aria-label="Key areas"><li>C#</li><li>ASP.NET Core</li><li>React</li><li>SQL</li><li>Application support</li><li>Technical troubleshooting</li><li>AWS learning</li></ul></div></div></header>
    <section className="journey-band"><div className="shell"><p className="eyebrow">Career journey</p><ol className="career-journey"><li><span>01</span>Technical Support</li><li><span>02</span>Software Development</li><li><span>03</span>UK Operational Leadership</li><li><span>04</span>Current Software and Cloud Projects</li></ol></div></section>
    <section className="section"><div className="shell about-layout"><article className="prose"><h2>Technical background</h2><p>My background includes a B.Tech in Software Technology and MSc IT studies at UWE Bristol. I have previous software engineering experience, previous technical support experience and working knowledge of C#, .NET, React, TypeScript and SQL. I am also developing my AWS cloud knowledge.</p><p>I approach software as an operational tool rather than an isolated technical exercise. Requirements, accessibility, security, diagnostics and recovery all influence whether an application is genuinely useful.</p><h2>Operational experience that strengthens my IT work</h2><p>My current UK operational and supervisory experience builds leadership, responsibility, compliance awareness, customer service, problem solving, team coordination and business-process understanding. These strengths are valuable in application support and software delivery, where clear communication and calm ownership matter alongside technical ability.</p><p>This current role is part of my professional story, but it does not replace my software direction. I am actively positioning for software development, application support, IT support, systems and junior cloud opportunities.</p><h2>How I work</h2><p>I prefer honest scope, maintainable solutions and visible trade-offs. Portfolio concepts are labelled as concepts or architecture studies, and proposed technologies are separated from implemented ones.</p><p>Continue to the <Link href="/experience">experience timeline</Link>, inspect my <Link href="/projects">software project case studies</Link>, or <Link href="/contact">discuss a suitable opportunity</Link>.</p></article><aside className="side-card profile-summary"><strong>Professional summary</strong><ul><li>Based in Newtown, Powys</li><li>Available for Wales-based, hybrid and UK remote roles</li><li>Interested in development, support, systems and junior cloud work</li></ul><Link className="button" href="/contact">Contact me</Link></aside></div></section>
  </>;
}
